version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
    
    webserver:
        image: airflow-local:0.2
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAC_EX=n
            - EXECUTOR=Local
            - GOOGLE_APPLICATION_CREDENTIALS=${GCP_CRED}
        volumes:
            - ./dags:/usr/local/airflow/dags
        ports:
            - "9000:8080"
        command: webserver
